FROM ruby:2.5.1
RUN groupadd jenkins
RUN useradd -r -u 1001 -g jenkins jenkins
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev \
            postgresql sudo curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | \
    bash - && apt-get install -y nodejs 
USER 1001
